apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: NodePort             # Expone el Service en un puerto del nodo (30000-32767)
  selector:
    app: flask               # Envía tráfico a los Pods con esta etiqueta
  ports:
    - port: 5000             # Puerto del Service dentro del clúster
      targetPort: 5000       # Puerto del contenedor
      nodePort: 30080        # Puerto expuesto en el nodo